### PR TITLE
chore: add deepinid icon

### PR DESCRIPTION
**Pull request by Decodetalkers**
seems the icon is missing..

Log:

### CODE REVIEW

**Review by myml — APPROVED** [review]

**Review by wineee — CHANGES_REQUESTED** [review]
also need  rename in cmake
https://github.com/linuxdeepin/deepin-deepinid-plugin/blob/8fa1be9a6781be23a6fba127d7c5ce81511d4564/dcc-deepinid-plugin/CMakeLists.txt#L78

**Comment by Decodetalkers** [comment]
> also need rename in cmake
> 
> https://github.com/linuxdeepin/deepin-deepinid-plugin/blob/8fa1be9a6781be23a6fba127d7c5ce81511d4564/dcc-deepinid-plugin/CMakeLists.txt#L78

不需要安装了，原来它是有安装逻辑的啊

**Review by wineee — APPROVED** [review]

**Comment by Decodetalkers** [comment]
- https://github.com/linuxdeepin/developer-center/issues/6472

**Pull request merged**
